/*
 * Copyright (C) 2022-2026 Aloysius Indrayanto
 *
 * This file is part of the JxMake program, see LICENSE file for the license details.
 */


package jxm.tool;


import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

import java.util.concurrent.ConcurrentHashMap;

import jxm.*;
import jxm.xb.*;


public class I18N {

    /*
     * To dump the translation file with the correct content:
     *     # Set the appropriate environment variable, for example:
     *           export JXMAKE_I18N_CAPTURE_FILE=/tmp/test.po
     *     # Run the JxMake Script Editor, then:
     *           # Open the Console   so all related texts are included in the dump
     *           # Open the About box so all related texts are included in the dump
     */

    private static final String              _captureFile  = SysUtil.getEnv("JXMAKE_I18N_CAPTURE_FILE", null);
    private static final Map<String, String> _translations = (_captureFile == null)
                                                           ?                              new ConcurrentHashMap<>()
                                                           : Collections.synchronizedMap( new LinkedHashMap    <>() );

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    public static String _T(final String id)
    {
        String str = null;

        if(_captureFile != null) str = _translations.computeIfAbsent( id, k -> "" );
        else                     str = _translations.get(id);

        return ( str != null && !str.isEmpty() ) ? str : id;
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    private static final StringBuilder _sbEscapeUnescape = new StringBuilder();

    private static String _escape(final String s)
    {
        final StringBuilder sb = _sbEscapeUnescape;
        sb.setLength(0);

        for( char c : s.toCharArray() ) {

            switch(c) {
                case '\f'     : sb.append("\\f" ); break;
                case '\n'     : sb.append("\\n" ); break;
                case '\r'     : sb.append("\\r" ); break;
                case '\t'     : sb.append("\\t" ); break;
                case '\u000B' : sb.append("\\v" ); break;
                case '"'      : sb.append("\\\""); break;
                case '\\'     : sb.append("\\\\"); break;
                default       : sb.append(c     ); break;
            }

        } // for

        return sb.toString();
    }

    private static String _unescape(final String s)
    {
        final StringBuilder sb = _sbEscapeUnescape;
        sb.setLength(0);

        for( int i = 0; i < s.length(); ++i ) {

            final char c = s.charAt(i);

            if( c == '\\' && i + 1 < s.length() ) {

                final char next = s.charAt(i + 1);

                switch(next) {

                    case 'f'  : sb.append('\f'    ); ++i; break;
                    case 'n'  : sb.append('\n'    ); ++i; break;
                    case 'r'  : sb.append('\r'    ); ++i; break;
                    case 't'  : sb.append('\t'    ); ++i; break;
                    case 'v'  : sb.append('\u000B'); ++i; break;
                    case '"'  : sb.append("\""    ); ++i; break;
                    case '\\' : sb.append("\\"    ); ++i; break;
                    default   : sb.append(c       );      break;
                }

            }
            else {
                sb.append(c);
            }

        } // for

        return sb.toString();
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    private static void _saveTranslationFile()
    {
        try(
            final PrintWriter pw = new PrintWriter( new FileWriter(_captureFile) )
        ) {

            pw.println( "#"                                                                                       );
            pw.println( "# JxMake Translation File (.po)"                                                         );
            pw.printf ( "# Generated by JxMake %s\n",  SysUtil.jxmVerString()                                     );
            pw.println( "#"                                                                                       );
            pw.println( "# This file serves as the base for your translations."                                   );
            pw.println( "#"                                                                                       );
            pw.println( "# JxMake only supports the basic features:"                                              );
            pw.println( "#     - Simple msgid and msgstr pairs"                                                   );
            pw.println( "#     - Limited escape sequence processing (\\ooo, \\xNN, etc. are not supported)"       );
            pw.println( "#     - No multiline msgid and msgstr entries"                                           );
            pw.println( "#     - No context entries (msgctxt)"                                                    );
            pw.println( "#     - No special comments support (context, selector, workflow flags)"                 );
            pw.println( "#"                                                                                       );
            pw.println( "# Note:"                                                                                 );
            pw.println( "#     - Some strings contain tags or markers that will be interpreted by the UI."        );
            pw.println( "#     - Do not remove or translate these elements; only translate the surrounding text." );
            pw.println( "#"                                                                                       );
            pw.println( "# Edit with care to ensure compatibility with JxMake."                                   );
            pw.println( "#\n" );

            for( final Map.Entry<String, String> kv : _translations.entrySet() ) {

                pw.printf( "msgid \"%s\"\n" , _escape( kv.getKey  () ) );
                pw.printf( "msgstr \"%s\"\n", _escape( kv.getValue() ) );

                pw.println();

            } // for

        }
        catch(final IOException e) {
            // Print the stack trace if requested
            if( XCom.enableAllExceptionStackTrace() ) e.printStackTrace();
        }
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////////

    static {

        final String[] tfs = new String[] {
                                 SysUtil._JxMakeLanguageCountry  ,
                                 SysUtil._JxMakeLanguageCountryFB,
                                 SysUtil._JxMakeLanguage
                             };

        String text = null;

        for(final String tf : tfs) {
            try {
                text = SysUtil.loadTextResource( SysUtil.getTranslationFileURL_defLoc(tf) );
                if(text != null) break;
            }
            catch(final Exception ignored) {}
        }

        if(text == null && _captureFile != null) {
            try {
                text = SysUtil.readTextFileAsString(_captureFile);
            }
            catch(final Exception ignored) {}
        }

        if(text != null) {
            try(
                final BufferedReader br = new BufferedReader( new StringReader(text) )
            ) {

                while(true) {

                    // Read until we find 'msgid'
                    String msgid = null;

                    while(true) {

                        msgid = br.readLine();

                        if( msgid == null                ) break;
                        if( msgid.trim().isEmpty()       ) continue;
                        if( msgid.trim().startsWith("#") ) continue;
                        if( msgid.startsWith("msgid ")   ) break;

                    } // while

                    // Read until we find 'msgstr'
                    String msgstr = null;

                    while(true) {

                        msgstr = br.readLine();

                        if( msgstr == null                ) break;
                        if( msgstr.trim().isEmpty()       ) continue;
                        if( msgstr.trim().startsWith("#") ) continue;
                        if( msgstr.startsWith("msgstr ")  ) break;

                    } // while

                    if(msgstr == null) break;

                    // Extract quoted parts
                    String key = null;
                    String val = null;

                    if( msgid .length() > 7 && msgid .charAt(6) == '"' && msgid .endsWith("\"") ) key = msgid .substring( 7, msgid .length() - 1 );
                    if( msgstr.length() > 8 && msgstr.charAt(7) == '"' && msgstr.endsWith("\"") ) val = msgstr.substring( 8, msgstr.length() - 1 );

                    if( key == null || val == null ) continue;

                    // Put the translations
                    key = _unescape(key);
                    val = _unescape(val);

                    /*
                    SysUtil.stdDbg().println(key);
                    SysUtil.stdDbg().println(val);
                    SysUtil.stdDbg().println(   );
                    //*/

                    _translations.put(key, val);

                } // while
            }
            catch(final IOException e) {
                // Print the stack trace if requested
                if( XCom.enableAllExceptionStackTrace() ) e.printStackTrace();
            }
        }


        // Register shutdown hook to save the translation file
        if(_captureFile != null) {
            Runtime.getRuntime().addShutdownHook( new Thread(
                () -> _saveTranslationFile()
            ) );
        }
    }

} // class I18N
