#####
##### Copyright (C) 2022-2026 Aloysius Indrayanto
#####
##### This file is part of the JxMake program, see LICENSE file for the license details.
#####


include ../ATmega8A_Common/atmega8a.mk

TARGET_FIRMWARE_HEX_FILE_NAME  = Firmware-JxMakeHVA_BoostSection.hex
MACROS                        += -DCALIBRATE_VR=0
