[CLASS:jxm.ugc.ProgPIC16$Config@0x0000090900000001]

cmdPIC.LoadConfiguration            = 0x00
cmdPIC.LoadDataForProgMem           = 0x02
cmdPIC.LoadDataForDataMem           = 0x03
cmdPIC.IncrementAddress             = 0x06
cmdPIC.ResetAddress                 = 0x16
cmdPIC.ReadDataFromProgMem          = 0x04
cmdPIC.ReadDataFromDataMem          = 0x05
cmdPIC.BeginErase                   = 0x08
cmdPIC.BeginEraseProgCycle          = 0x08
cmdPIC.BeginProgOnlyCycle           = 0x18
cmdPIC.BeginIntTimedProg            = 0x08
cmdPIC.BeginExtTimedProg            = 0x08
cmdPIC.EndExtTimedProg              = 0x0E
cmdPIC.RowEraseProgMem              = 0x11
cmdPIC.BulkEraseProgMem             = 0x09
cmdPIC.BulkEraseDataMem             = 0x0B
cmdPIC.BulkEraseSetup1              = 0x01
cmdPIC.BulkEraseSetup2              = 0x07
cmdPIC.ChipErase                    = 0x1F
cmdPIC.BeginProgramming             = 0x08
cmdPIC.EndProgramming               = 0x17

#define ::: CST = jxm.ugc.ProgPIC16$CmdSeq :::

baseProgSpec.configMemAddressBeg    = 0x000003FE
baseProgSpec.deviceIDWordLocOfsset  = 0
baseProgSpec.flashEAddressEmptyVal  = 0xFF
baseProgSpec.flashOAddressEmptyVal  = 0x0F
baseProgSpec.flashAddressPreInc     = 1
baseProgSpec.cmdChipErase_Unlock    = null
baseProgSpec.cmdChipErase_Flash     = #{CST}                                                                         \
                                      $CS_ResetAddress  , $BulkEraseProgMem , $CS_DelayMS       , 0x0000000000000014
;                                     0x0000000000000064, 0x00000000000007DE, 0x0000000000000001, 0x0000000000000014
baseProgSpec.cmdChipErase_EEPROM    = null
baseProgSpec.cmdChipErase_Recover   = null
baseProgSpec.cmdChipErase_Unbrick   = null
baseProgSpec.cmdLoadConfiguration   = #{CST} $CS_NotSupported
baseProgSpec.cmdIncrementAddress    = #{CST} $IncrementAddress
baseProgSpec.cmdResetAddress        = #{CST} $_INVALID_
baseProgSpec.cmdLoadDataForProgMem  = #{CST} $LoadDataForProgMem
baseProgSpec.cmdLoadDataForDataMem  = #{CST} $CS_NotSupported
baseProgSpec.cmdReadDataFromProgMem = #{CST} $ReadDataFromProgMem
baseProgSpec.cmdReadDataFromDataMem = #{CST} $CS_NotSupported
baseProgSpec.cmdWriteFlash          = #{CST} $BeginExtTimedProg
baseProgSpec.cmdWriteFlashDelayMS   = 0x0002
baseProgSpec.cmdWriteFlashEnd       = #{CST} $EndExtTimedProg
baseProgSpec.cntWriteFlashMulti     = 1
baseProgSpec.msbAlignEEPROMData     = false
baseProgSpec.cmdWriteEEPROM         = #{CST} $CS_NotSupported
baseProgSpec.cmdWriteEEPROMNoErase  = #{CST} $CS_NotSupported
baseProgSpec.cmdWriteEEPROMDelayMS  = #{CST} $CS_NOP
baseProgSpec.cmdWriteEEPROMEnd      = #{CST} $_INVALID_
baseProgSpec.cmdWriteConfig         = #{CST} $BeginExtTimedProg
baseProgSpec.cmdWriteConfigDelayMS  = 0x0002
baseProgSpec.cmdWriteConfigEnd      = #{CST} $EndExtTimedProg
baseProgSpec.part                   = PIC16
baseProgSpec.subPart                = F
baseProgSpec.mode                   = HVSimple
baseProgSpec.entrySeq               = -1

memoryFlash.address                 = 0x00000000
memoryFlash.totalSize               = 1024
memoryFlash.eraseBlockSize          = 64
memoryFlash.writeBlockSize          = 2
memoryFlash.eraseBlockSizeE         = -1
memoryFlash.writeBlockSizeE         = -1
memoryFlash.readDataBuff            = null

memoryEEPROM.addressBeg             = -1
memoryEEPROM.addressEnd             = -1
memoryEEPROM.totalSize              = 0
memoryEEPROM.writeBlockSizeE        = -1
memoryEEPROM.addressMulFW           = 2
memoryEEPROM.addressOfsFW           = 0x00000000

memoryConfigBytes.addressBeg        = 0x000003FE
memoryConfigBytes.addressEnd        = 0x00000400
memoryConfigBytes.address           = 0x000003FE
memoryConfigBytes.addressFW         = null
memoryConfigBytes.size              = 2
memoryConfigBytes.bitMask           = 0x0000000F
memoryConfigBytes.orgMask           = null
memoryConfigBytes.clrMask           = null
memoryConfigBytes.setMask           = null
memoryConfigBytes.maxTotalSize      = 0
memoryConfigBytes.addressMulFW      = 1
memoryConfigBytes.addressOfsFW      = 0x00001C00
memoryConfigBytes.prepadFWSize      = -1
memoryConfigBytes.prepadFWBegA      = -1
memoryConfigBytes.prepadValue       = 0x00
memoryConfigBytes.prepadSizeFW      = -1
memoryConfigBytes.prepadAddrFW      = -1
memoryConfigBytes.prepadByteFW      = 0x00
