#####
##### Copyright (C) 2022-2026 Aloysius Indrayanto
#####
##### This file is part of the JxMake program, see LICENSE file for the license details.
#####


include ../ATtiny44A_Power_Supply_Control___Common/attiny44a_5v_8mhz.mk

TARGET_FIRMWARE_HEX_FILE_NAME  = Firmware-JxMakePSC_Selector.hex
MACROS                        += -DVIN2_PRIMARY
