#####
##### Copyright (C) 2022-2026 Aloysius Indrayanto
#####
##### This file is part of the JxMake program, see LICENSE file for the license details.
#####


include atmega1284p.mk

TARGET_FIRMWARE_HEX_FILE_NAME  = Firmware-JxMakeHVA_II.hex
DEBUG_HW_UART_BAUD             = 460800UL
UPDI_HW_UART_BAUD              =  19200UL
MACROS                        += -DUPDI_USE_HW_UART
