#####
##### Copyright (C) 2022-2026 Aloysius Indrayanto
#####
##### This file is part of the JxMake program, see LICENSE file for the license details.
#####


include ../arduino_pro_mini_3v3_8mhz_ssd1306ascii.mk

SKETCH_FILE_NAME := ATmega328P_4Digit_Voltmeter.ino
RESULT_FILE_NAME := ../Firmware-JxMakeVM4.hex
