/*
 * Copyright (C) 2022-2026 Aloysius Indrayanto
 *
 * This file is part of the JxMake build system and is distributed under the Apache License, Version 2.0.
 * See the LICENSE file in the formatter root directory for the full Apache License, Version 2.0 text.
 */

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.LinkedHashMap;
import java.util.Map;

import com.jxmake.formatter.Lang;
import com.jxmake.formatter.classifier.CommentClassifier;
import com.jxmake.formatter.classifier.CommentDecision;
import com.jxmake.formatter.classifier.CommentFeatureExtractor;
import com.jxmake.formatter.classifier.CommentFeatureVector;
import com.jxmake.formatter.classifier.gru.GruClassifier;

/** Auto-labels a real comment corpus via the existing rule-based (linear) {@link CommentClassifier}
 *  to produce {@code tools/gru/sample_default.txt}, an RDD_EXT_20/21-schema labeled-examples file
 *  for {@code GruTrainer} -- replaces the old "extract corpus, archive raw, hand-label later"
 *  workflow for the default training set (Pool A/Pool B hand-labeling per {@code acquire_corpus.sh}
 *  remains available separately for growing the corpus further; this tool does not replace that).
 *
 *  <p>Reads the same corpus format {@code extract_comments.py} writes and
 *  {@code CommentAbstainTally}/{@code ExtractPoolA} read ({@code "<lang>\t<escaped comment text>"}).
 *  For each comment, runs the real {@link CommentFeatureExtractor#extract(String, Lang)} /
 *  {@link CommentClassifier#classify} pipeline (the same pipeline production code uses, not a
 *  reimplementation) and keeps only the comments the rule-based classifier resolves with high
 *  confidence ({@code YES} or {@code NO}) -- {@code ABSTAIN} comments are exactly the cases that
 *  still need a human label (or a deployed GRU) and are skipped here, never auto-labeled.
 *
 *  <p><b>Known current limitation (see STATE_AI.md):</b> the rule-based classifier's own
 *  {@code classify} method has no code path that produces {@code NO} today (RDD_KEY_96) -- every
 *  comment that reaches this tool's output is therefore currently labeled {@code YES}. This is a
 *  faithful reflection of the rule-based classifier's real behavior, not a bug in this tool; fixing
 *  it is a separate future task against {@code CommentClassifier} itself.
 *
 *  <p>Target-word index (RDD_EXT_21): comments kept via {@link CommentFeatureVector#hasLeadingKeywordMatch}
 *  (the keyword-ambiguity gate resolving to YES) use index 0 (the leading keyword), matching Pool
 *  A's own convention. Every other kept comment has no single ambiguous target word -- the decision
 *  covers the whole comment, not one token -- so index 0 (the first token) is used as a stable
 *  placeholder, teaching the GRU "this whole comment is an unambiguous/easy case" rather than
 *  pointing at a specific word.
 *
 *  <p>Lives outside {@code src/}, same as {@code GruTrainer.java}/{@code CommentAbstainTally.java}/
 *  {@code ExtractPoolA.java} -- a one-off data-preparation tool, not runtime or shipped code. */
public final class GenerateSampleDefault {

    private GenerateSampleDefault() {
    }

    private static final String USAGE = "Usage: GenerateSampleDefault <combined-comments-path> <output-path>";

    /** Header written to the top of every generated {@code sample_default.txt}, documenting
     *  provenance per the user's explicit request -- lines starting with {@code #} are already
     *  skipped by {@code GruTrainer.readExamples}, same convention as {@code sample_examples.txt}. */
    private static final String[] HEADER = {
        "# tools/gru/sample_default.txt -- auto-generated GRU training corpus.",
        "# This corpus is obtained from local project directories owned by me and from external",
        "# repositories under an MIT/Apache-2.0/BSD-3-Clause license.",
        "# Generated by `make gru-acquire-corpus` (tools/gru/GenerateSampleDefault.java): every",
        "# line is a real comment auto-labeled by the existing rule-based CommentClassifier's",
        "# high-confidence (YES/NO) decisions -- ABSTAIN comments are excluded, not auto-labeled.",
        "# Regenerate by re-running `make gru-acquire-corpus`; do not hand-edit.",
    };

    public static void main(final String[] args) throws IOException {
        if (args.length != 2) {
            System.err.println(USAGE);
            System.exit(2);
            return;
        }

        final java.io.File input = new java.io.File(args[0]);
        if (!input.isFile() || !input.canRead()) {
            System.err.println("GenerateSampleDefault: input file not readable: " + args[0]);
            System.exit(2);
            return;
        }

        final Map<String, Lang> langCache = new LinkedHashMap<String, Lang>();
        int total = 0;
        int malformed = 0;
        int kept = 0;
        int yesCount = 0;
        int noCount = 0;

        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(Files.newInputStream(input.toPath()), StandardCharsets.UTF_8));
             BufferedWriter writer = new BufferedWriter(
                new OutputStreamWriter(Files.newOutputStream(new java.io.File(args[1]).toPath()),
                        StandardCharsets.UTF_8))) {
            for (final String headerLine : HEADER) {
                writer.write(headerLine);
                writer.newLine();
            }

            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isEmpty()) {
                    continue;
                }
                final int tab = line.indexOf('\t');
                if (tab < 0) {
                    malformed++;
                    continue;
                }
                total++;
                final String langName = line.substring(0, tab);
                final String escapedText = line.substring(tab + 1);
                final String commentText = unescape(escapedText);

                final Lang lang = langCache.computeIfAbsent(langName, Lang::new);
                final CommentFeatureVector features = CommentFeatureExtractor.extract(commentText, lang);
                final CommentDecision decision = CommentClassifier.classify(features);

                if (decision != CommentDecision.YES && decision != CommentDecision.NO) {
                    continue;
                }
                if (GruClassifier.tokenize(commentText).isEmpty()) {
                    continue;
                }

                writer.write(langName);
                writer.write('\t');
                writer.write(decision.name());
                writer.write('\t');
                writer.write("0");
                writer.write('\t');
                writer.write(escapedText);
                writer.newLine();
                kept++;
                if (decision == CommentDecision.YES) {
                    yesCount++;
                } else {
                    noCount++;
                }
            }
        }

        System.out.println("GenerateSampleDefault: " + total + " comment(s) read (" + malformed
                + " malformed line(s) skipped), " + kept + " auto-labeled and kept (YES=" + yesCount
                + ", NO=" + noCount + ")");
    }

    private static String unescape(final String escaped) {
        final StringBuilder sb = new StringBuilder(escaped.length());
        for (int i = 0; i < escaped.length(); i++) {
            final char c = escaped.charAt(i);
            if (c == '\\' && i + 1 < escaped.length()) {
                final char next = escaped.charAt(i + 1);
                if (next == 'n') {
                    sb.append('\n');
                    i++;
                    continue;
                }
                if (next == 't') {
                    sb.append('\t');
                    i++;
                    continue;
                }
                if (next == '\\') {
                    sb.append('\\');
                    i++;
                    continue;
                }
            }
            sb.append(c);
        }
        return sb.toString();
    }
}
