/*
 * Copyright (C) 2024 Example Corp.
 * SPDX-License-Identifier: MIT
 */

//%JXM_CFMT_CFG line-split-by-operator-priority=on

type PathCompareFunctionTypeAliasNameHereXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX = (containerParamNameHereAAAAAAAAAAAAAAAAAAAAAAAAAAAA: SomeContainerTypeNameHereBBBBBBBBBBBBBBBBBBBBBBBBBBBBB, containeeParamNameHereCCCCCCCCCCCCCCCCCCCCCCCCCCCCC: SomeContaineeTypeNameHereDDDDDDDDDDDDDDDDDDDDDDDDDDDDD) => boolean;

function computeCacheStateWithNullishFallbackXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX(injectorValueHereAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA: { get(): unknown } | null): unknown {
    const cacheStateResultValueHereYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY = injectorValueHereAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA?.get() ?? { isActiveFlagNameHereZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ: false };
    return cacheStateResultValueHereYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY;
}
